version: "3.1"
services:

    mariadb:
      image: mariadb:10.4
      container_name: jesse-mariadb
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=jesse
        - MYSQL_USER=jesse
        - MYSQL_PASSWORD=root
      ports:
        - "8101:3306"

    webserver:
      image: nginx:alpine
      container_name: jesse-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./phpdocker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
       - "8098:80"

    php-fpm:
      build: phpdocker/php-fpm
      container_name: jesse-php-fpm
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

    cron-jobs:
      build: phpdocker/php-fpm
      container_name: jesse-cron-jobs
      working_dir: /application
      volumes:
        - .:/application
        - ./phpdocker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini

